version: "3.8"
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - db
    networks:
      - sonar-network

  db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonar-network

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    depends_on:
      - sonarqube
    networks:
      - sonar-network
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_LOGIN: sqa_54fd0efaba67873bbbf09dce13e5c2523dfee9b4
    volumes:
      - ./src:/usr/src

networks:
  sonar-network:
    driver: bridge
